#!/usr/bin/env python3
"""
AutoDock Vina docking pipeline for top 100 G-group compounds into VDR LBD.

PROTEIN: 1DB1 crystal structure (Rochel et al., Mol Cell, 2000)
  - Experimental VDR LBD at 1.80 Å resolution
  - Chain A: residues 120-423 (250 resolved residues)
  - Disordered gaps: 165-215 (insertion domain), 375-377 (loop)
  - Co-crystal ligand: 1α,25(OH)₂D₃ (calcitriol) — removed for docking
  - Original PDB numbering preserved (matches UniProt P11473)

PREPARATION (via prepare_1db1_receptor.py):
  - PDBFixer: added missing sidechain atoms within resolved residues
  - Hydrogens added at pH 7.4 (OpenMM)
  - Histidine protonation: HID (δ-tautomer), NE2 = H-bond acceptor
  - His305/His397: NE2 lone pairs both accept calcitriol 25-OH (crystal contacts)
  - 439 polar H (HD type) for H-bond donor recognition
  - Gasteiger partial charges assigned
  - AutoDock atom types: C, A, N, NA, OA, S, HD
  - 1589 non-polar H stripped

Workflow per compound:
  1. SMILES -> 3D conformer (RDKit ETKDGv3 + MMFF)
  2. 3D mol -> PDBQT (meeko)
  3. Vina docking into LBD binding pocket
  4. Extract best pose, merge receptor+ligand -> complex PDB
  5. Parse scores, validate ligand placement

Enhanced settings vs previous version:
  - 1DB1 crystal receptor (250 res, 1.80 Å) — gold-standard for VDR docking
  - Original PDB residue numbering (120-423) matches literature conventions
  - Proper protein preparation: polar H, pH 7.4, Gasteiger charges
  - Grid box computed from 12 crystal binding pocket residues incl. His305/His397
  - Exhaustiveness 64 (publication quality), seed for reproducibility
  - Complex PDB output with proper chain IDs (A=protein, B=ligand)

Glide XP-informed enhancements (Friesner et al. J Med Chem 2004, 2006):
  - Multi-state ligand prep: tautomer enumeration (RDKit MolStandardize)
    + multi-conformer generation (different ETKDG seeds) [--multi-state]
  - Pharmacophore validation: H-bond distances to 6 VDR anchors (1DB1 crystal)
    25-OH: His305-NE2, His397-NE2 | 1α-OH: Arg274-NH*, Ser237-OG
    3β-OH: Tyr143-OH, Ser278-OG   (all always reported)
  - Per-compound H-bond satisfaction count and pharmacophore score
  - Summary statistics: H-bond distribution across all compounds

Usage:
    python scripts/run_vina_docking.py                        # single-state (default)
    python scripts/run_vina_docking.py --multi-state          # tautomer x conformer
    python scripts/run_vina_docking.py --multi-state --max-tautomers 5 --max-conformers 5
    python scripts/run_vina_docking.py --limit 5              # test 5
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem
from meeko import MoleculePreparation, PDBQTWriterLegacy
from rdkit.Chem.MolStandardize import rdMolStandardize

# ===================================================================
# PATHS
# ===================================================================
ROOT = Path(__file__).resolve().parent.parent
MANIFEST_PATH = ROOT / "pdb" / "top100_g_complexes" / "manifest.csv"
OUTPUT_DIR = ROOT / "results" / "vina_docking"

# Prepared receptor (1DB1 crystal VDR LBD, 250 res, polar H, Gasteiger charges)
# Generated by: python scripts/prepare_1db1_receptor.py
RECEPTOR_PDBQT = ROOT / "pdb" / "vdr_1db1_prepared.pdbqt"
RECEPTOR_PDB = ROOT / "pdb" / "vdr_1db1_prepared.pdb"

# Flexible-residue receptor files (generated by prepare_1db1_receptor.py)
RECEPTOR_RIGID = ROOT / "pdb" / "vdr_1db1_rigid.pdbqt"
RECEPTOR_FLEX  = ROOT / "pdb" / "vdr_1db1_flex.pdbqt"

# Vina executable
VINA_EXE = r"C:\Program Files (x86)\The Scripps Research Institute\Vina\vina.exe"

# ===================================================================
# BINDING POCKET — search box in Boltz coordinate frame
# ===================================================================
# Computed from 12 key binding residues in 1DB1 crystal (original PDB numbering):
#   [143(Tyr), 145(Pro), 227(Leu), 233(Leu), 237(Ser),
#    269(Glu), 271(Ile), 272(Met), 274(Arg), 278(Ser),
#    305(His), 397(His)]
# Source: 1DB1 crystal structure (Rochel et al. 2000) + pdbfixer pH 7.4
BOX_CENTER = (11.89, 20.81, 36.97)
BOX_SIZE = (26.0, 26.0, 26.0)      # 17,576 A^3 — well within Vina limit

# 1DB1 binding residue numbers (original PDB numbering)
# Includes His305/His397 which both H-bond calcitriol 25-OH (1DB1 crystal)
VDR_LBD_BINDING = [143, 145, 227, 233, 237, 269, 271, 272, 274, 278, 305, 397]

# Pharmacophoric anchors — 1DB1 crystal H-bond network (Rochel et al. 2000)
# 25-OH:  His305 NE2 accepts (2.81 Å) + His397 NE2 accepts (2.82 Å)
# 1α-OH:  Arg274 NH1 donates  (2.86 Å) + Ser237 OG donates  (2.78 Å)
# 3β-OH:  Tyr143 OH donates  (2.83 Å) + Ser278 OG donates  (2.91 Å)
# Residue numbers: original 1DB1 PDB numbering (120-423)
PHARMACOPHORE = {
    305: {"name": "His305", "atoms": ["NE2"]},           # 25-OH acceptor
    397: {"name": "His397", "atoms": ["NE2"]},           # 25-OH acceptor
    274: {"name": "Arg274", "atoms": ["NH1", "NH2", "NE"]},  # 1α-OH donor
    237: {"name": "Ser237", "atoms": ["OG"]},            # 1α-OH donor
    143: {"name": "Tyr143", "atoms": ["OH"]},            # 3β-OH donor
    278: {"name": "Ser278", "atoms": ["OG"]},            # 3β-OH donor
}
HBOND_DIST_CUTOFF = 3.2   # Å — tightened for publication-quality H-bond scoring


# ===================================================================
# LIGAND PREPARATION
# ===================================================================
def smiles_to_pdbqt(smiles: str, name: str, out_dir: Path,
                    max_attempts: int = 5) -> tuple[bool, str, Path | None]:
    """Convert SMILES to PDBQT via RDKit 3D + meeko.

    Returns (success, message, pdbqt_path).
    """
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return False, "RDKit parse failed", None

    mol = Chem.AddHs(mol)

    # Try multiple random seeds for 3D embedding
    params = AllChem.ETKDGv3()
    embedded = False
    for attempt in range(max_attempts):
        params.randomSeed = 42 + attempt
        status = AllChem.EmbedMolecule(mol, params)
        if status == 0:
            embedded = True
            break

    if not embedded:
        # Fallback: random coordinates with more iterations
        params.useRandomCoords = True
        params.maxIterations = 2000
        status = AllChem.EmbedMolecule(mol, params)
        if status != 0:
            return False, f"3D embed failed after {max_attempts} attempts", None

    # Force field optimisation (MMFF preferred, UFF fallback)
    try:
        res = AllChem.MMFFOptimizeMolecule(mol, maxIters=1000)
        if res != 0:
            AllChem.UFFOptimizeMolecule(mol, maxIters=1000)
    except Exception:
        try:
            AllChem.UFFOptimizeMolecule(mol, maxIters=1000)
        except Exception:
            pass  # proceed with unoptimised coords

    # Meeko PDBQT conversion
    try:
        prep = MoleculePreparation()
        mol_setups = prep.prepare(mol)
        pdbqt_str, is_ok, err_msg = PDBQTWriterLegacy.write_string(
            mol_setups[0])
    except Exception as e:
        return False, f"meeko error: {e}", None

    if not pdbqt_str or len(pdbqt_str.strip()) < 50:
        return False, "empty PDBQT output", None

    # Fix invalid meeko atom types (CG0, G0, etc.) that crash Vina
    pdbqt_str = _fix_meeko_atom_types(pdbqt_str)

    pdbqt_path = out_dir / f"{name}.pdbqt"
    pdbqt_path.write_text(pdbqt_str, encoding="utf-8")
    return True, "OK", pdbqt_path


def _fix_meeko_atom_types(pdbqt_str: str) -> str:
    """Fix invalid AutoDock atom types produced by meeko.

    Meeko sometimes outputs non-standard types like CG0, G0, CG1 for
    complex ring systems (spiro, bridged, etc.).  Vina only accepts
    standard AD4 types: C, A, N, NA, OA, S, SA, HD, H, F, Cl, Br, I, P.

    Strategy:
      CG0 / CG1 / CG2 -> C   (carbon)
      G0 / G1          -> C   (meeko "glue" pseudo-atom → treat as carbon)
      Lines with just "G" element that start with "ATOM" for G0 pseudo-atoms
      are dropped entirely since they are duplicates.
    """
    fixed_lines = []
    for line in pdbqt_str.splitlines():
        if not (line.startswith("ATOM") or line.startswith("HETATM")):
            fixed_lines.append(line)
            continue

        # Check last field (atom type at col 77+)
        if len(line) >= 78:
            ad_type = line[77:].strip()
        elif len(line) >= 70:
            # try splitting
            parts = line.split()
            ad_type = parts[-1] if parts else ""
        else:
            fixed_lines.append(line)
            continue

        # Fix known bad types
        if ad_type in ("CG0", "CG1", "CG2", "CG3"):
            # Replace atom type with C, fix atom name too
            line = line[:12] + " C  " + line[16:77] + " C "
            fixed_lines.append(line)
        elif ad_type in ("G0", "G1", "G2", "G3"):
            # These are meeko "glue" pseudo-atoms — skip entirely
            # They are duplicate coordinate entries that Vina can't parse
            continue
        else:
            fixed_lines.append(line)

    return "\n".join(fixed_lines)


# ===================================================================
# GLIDE-INFORMED MULTI-STATE LIGAND PREPARATION
# ===================================================================
def enumerate_tautomers(mol, max_n: int = 5):
    """Enumerate dominant tautomers (approximates Glide LigPrep / Epik).

    RDKit's TautomerEnumerator applies standard chemical transform rules
    for keto-enol, amide-imidic acid, 1,3-shifts, etc.
    Returns canonical tautomer first, then alternatives.
    """
    try:
        enumerator = rdMolStandardize.TautomerEnumerator()
        canonical = enumerator.Canonicalize(mol)
        seen = {Chem.MolToSmiles(canonical)}
        tautomers = [canonical]
        for taut in enumerator.Enumerate(mol):
            if len(tautomers) >= max_n:
                break
            smi = Chem.MolToSmiles(taut)
            if smi not in seen:
                seen.add(smi)
                tautomers.append(taut)
        return tautomers
    except Exception:
        return [mol]


def smiles_to_pdbqt_variants(
    smiles: str,
    name: str,
    out_dir: Path,
    max_tautomers: int = 3,
    max_conformers: int = 3,
) -> list[tuple[Path, str]]:
    """Generate multiple ligand variants following Glide LigPrep concepts.

    For each tautomer x conformer combination:
      1. Enumerate dominant tautomers (RDKit MolStandardize)
      2. Generate diverse 3-D conformers with different ETKDG seeds
      3. MMFF-optimize each conformer
      4. Convert to PDBQT via meeko

    Returns list of (pdbqt_path, variant_label) tuples.
    The best Vina score across all variants is kept.
    """
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return []

    tautomers = enumerate_tautomers(mol, max_tautomers)
    variants: list[tuple[Path, str]] = []

    for t_idx, taut in enumerate(tautomers):
        for c_idx in range(max_conformers):
            label = f"{name}_t{t_idx}_c{c_idx}"
            taut_h = Chem.AddHs(Chem.Mol(taut))   # fresh copy + H
            seed = 42 + c_idx * 17

            params = AllChem.ETKDGv3()
            params.randomSeed = seed
            status = AllChem.EmbedMolecule(taut_h, params)
            if status != 0:
                params.useRandomCoords = True
                params.maxIterations = 2000
                status = AllChem.EmbedMolecule(taut_h, params)
                if status != 0:
                    continue

            try:
                res = AllChem.MMFFOptimizeMolecule(taut_h, maxIters=1000)
                if res != 0:
                    AllChem.UFFOptimizeMolecule(taut_h, maxIters=1000)
            except Exception:
                try:
                    AllChem.UFFOptimizeMolecule(taut_h, maxIters=1000)
                except Exception:
                    pass

            try:
                prep = MoleculePreparation()
                mol_setups = prep.prepare(taut_h)
                pdbqt_str, _, _ = PDBQTWriterLegacy.write_string(
                    mol_setups[0])
            except Exception:
                continue

            if not pdbqt_str or len(pdbqt_str.strip()) < 50:
                continue

            p = out_dir / f"{label}.pdbqt"
            p.write_text(pdbqt_str, encoding="utf-8")
            variants.append((p, label))

    return variants


# ===================================================================
# VINA DOCKING
# ===================================================================
def run_vina(
    ligand_pdbqt: Path,
    out_dir: Path,
    name: str,
    *,
    receptor: Path = RECEPTOR_PDBQT,
    flex_receptor: Path | None = None,
    exhaustiveness: int = 64,
    num_modes: int = 9,
    energy_range: int = 4,
    seed: int = 42,
    timeout: int = 600,
) -> tuple[bool, str, float, float | None]:
    """Run Vina docking. Returns (success, msg, elapsed, best_score)."""
    out_pdbqt = out_dir / f"{name}_out.pdbqt"
    log_file = out_dir / f"{name}_log.txt"

    cmd = [
        VINA_EXE,
        "--receptor", str(receptor),
        "--ligand", str(ligand_pdbqt),
        *(["--flex", str(flex_receptor)] if flex_receptor else []),
        "--center_x", f"{BOX_CENTER[0]:.3f}",
        "--center_y", f"{BOX_CENTER[1]:.3f}",
        "--center_z", f"{BOX_CENTER[2]:.3f}",
        "--size_x", f"{BOX_SIZE[0]:.1f}",
        "--size_y", f"{BOX_SIZE[1]:.1f}",
        "--size_z", f"{BOX_SIZE[2]:.1f}",
        "--exhaustiveness", str(exhaustiveness),
        "--num_modes", str(num_modes),
        "--energy_range", str(energy_range),
        "--seed", str(seed),
        "--out", str(out_pdbqt),
        "--log", str(log_file),
    ]

    t0 = time.time()
    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True,
            timeout=timeout, cwd=str(ROOT),
        )
        elapsed = time.time() - t0

        if result.returncode != 0:
            err = (result.stderr or result.stdout or "unknown")[-400:]
            return False, f"exit {result.returncode}: {err}", elapsed, None

        best_score = parse_vina_log(log_file)
        return True, f"OK ({elapsed:.0f}s)", elapsed, best_score

    except subprocess.TimeoutExpired:
        return False, f"timeout after {timeout}s", time.time() - t0, None
    except Exception as exc:
        return False, str(exc), time.time() - t0, None


# ===================================================================
# LOG PARSING
# ===================================================================
def parse_vina_log(log_path: Path) -> float | None:
    """Parse best binding affinity (mode 1) from Vina log."""
    if not log_path.exists():
        return None
    try:
        text = log_path.read_text()
        in_results = False
        for line in text.splitlines():
            line = line.strip()
            if "-----+" in line:
                in_results = True
                continue
            if in_results and line and line[0].isdigit():
                parts = line.split()
                if len(parts) >= 2:
                    return float(parts[1])
    except Exception:
        pass
    return None


def parse_all_scores(log_path: Path) -> list[float]:
    """Parse all binding mode scores from Vina log."""
    scores = []
    if not log_path.exists():
        return scores
    try:
        text = log_path.read_text()
        in_results = False
        for line in text.splitlines():
            line = line.strip()
            if "-----+" in line:
                in_results = True
                continue
            if in_results and line and line[0].isdigit():
                parts = line.split()
                if len(parts) >= 2:
                    try:
                        scores.append(float(parts[1]))
                    except ValueError:
                        break
            elif in_results and not line:
                break
    except Exception:
        pass
    return scores


# ===================================================================
# POSE EXTRACTION & COMPLEX PDB ASSEMBLY
# ===================================================================
def extract_best_pose_pdbqt(vina_out_pdbqt: Path,
                            strip_flex: bool = True) -> str | None:
    """Extract MODEL 1 (best pose) from multi-model Vina output.

    When strip_flex=True (default), removes BEGIN_RES/END_RES blocks
    (flex-residue atoms from Vina --flex output), returning ligand only.
    This ensures create_complex_pdb() gets only ligand PDBQT lines.
    """
    if not vina_out_pdbqt.exists():
        return None
    lines = vina_out_pdbqt.read_text().splitlines()
    pose_lines = []
    in_model1 = False
    in_flex_res = False
    for line in lines:
        if line.startswith("MODEL"):
            model_num = line.split()[-1]
            if model_num == "1":
                in_model1 = True
            elif in_model1:
                break
        elif in_model1:
            if line.startswith("ENDMDL"):
                break
            # Strip flex-residue blocks from Vina --flex output
            if strip_flex:
                if line.startswith("BEGIN_RES"):
                    in_flex_res = True
                    continue
                if line.startswith("END_RES"):
                    in_flex_res = False
                    continue
                if in_flex_res:
                    continue
                if line.startswith(("ROOT", "ENDROOT", "BRANCH", "ENDBRANCH")):
                    continue
            pose_lines.append(line)
    return "\n".join(pose_lines) if pose_lines else None


# AutoDock atom type -> standard PDB element symbol
_AD_TYPE_TO_ELEMENT: dict[str, str] = {
    "C": "C",  "A": "C",                   # aliphatic / aromatic carbon
    "OA": "O", "OS": "O",                  # oxygen acceptor / sulfate O
    "N": "N",  "NA": "N", "NS": "N",       # nitrogen / acceptor / sulfonamide
    "HD": "H", "H": "H",  "HS": "H",       # hydrogen donor / plain H / S-H
    "S": "S",  "SA": "S",                  # sulfur / sulfur acceptor
    "P": "P",  "F": "F",  "I": "I",
    "Cl": "Cl", "Br": "Br",
    "Fe": "Fe", "Zn": "Zn", "Mg": "Mg", "Ca": "Ca", "Mn": "Mn",
}


def pdbqt_to_pdb_lines(pdbqt_text: str, chain: str = "B",
                       resname: str = "LIG", resnum: int = 1) -> list[str]:
    """Convert PDBQT ATOM lines to standard PDB HETATM lines."""
    pdb_lines = []
    serial = 1
    for line in pdbqt_text.splitlines():
        if not (line.startswith("ATOM") or line.startswith("HETATM")):
            continue
        try:
            x = float(line[30:38])
            y = float(line[38:46])
            z = float(line[46:54])
        except (ValueError, IndexError):
            continue

        atom_name = line[12:16].strip()

        # Read AutoDock atom type from PDBQT column 77-79
        ad_type = ""
        if len(line) >= 78:
            ad_type = line[77:79].strip()
        if not ad_type:
            ad_type = atom_name[0] if atom_name else "C"

        # Convert AutoDock atom type to standard PDB element symbol
        element = _AD_TYPE_TO_ELEMENT.get(ad_type, ad_type[0] if ad_type else "C")

        an = f" {atom_name:<3s}" if len(atom_name) < 4 else atom_name[:4]
        pdb_line = (
            f"HETATM{serial:5d} {an:4s} {resname:3s} {chain}{resnum:4d}    "
            f"{x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00          {element:>2s}  "
        )
        pdb_lines.append(pdb_line)
        serial += 1
    return pdb_lines


def create_complex_pdb(
    receptor_pdb: Path,
    docked_pdbqt: Path,
    output_pdb: Path,
) -> Path | None:
    """Merge receptor PDB (chain A) + best docked pose (chain B) into complex.

    Produces a properly formatted PDB with:
      - ATOM records for protein (chain A, res 120-423, 1DB1 numbering)
      - TER
      - HETATM records for ligand (chain B, LIG 1)
      - END
    """
    pose_text = extract_best_pose_pdbqt(docked_pdbqt)
    if pose_text is None:
        return None

    lig_lines = pdbqt_to_pdb_lines(pose_text, chain="B")
    if not lig_lines:
        return None

    # Read receptor PDB
    rec_lines = []
    last_serial = 0
    for line in receptor_pdb.read_text().splitlines():
        if line.startswith("ATOM"):
            # Ensure chain A is set
            fixed = line[:21] + "A" + line[22:]
            rec_lines.append(fixed)
            try:
                last_serial = int(line[6:11].strip())
            except ValueError:
                pass

    # TER after last protein atom, referencing last protein residue
    ter_serial = last_serial + 1
    # Find last protein residue name/number for proper TER record
    last_resname = "UNK"
    last_resnum = 0
    for rl in reversed(rec_lines):
        if rl.startswith("ATOM"):
            last_resname = rl[17:20].strip()
            try:
                last_resnum = int(rl[22:26].strip())
            except ValueError:
                pass
            break

    # Renumber ligand serials continuing after TER
    renumbered_lig = []
    for i, ll in enumerate(lig_lines, start=1):
        new_serial = ter_serial + i
        renumbered_lig.append(f"{ll[:6]}{new_serial:5d}{ll[11:]}")

    # Assemble
    out_lines = rec_lines
    out_lines.append(
        f"TER   {ter_serial:5d}      {last_resname:>3s} A{last_resnum:4d}")
    out_lines.extend(renumbered_lig)
    out_lines.append("END")

    output_pdb.write_text("\n".join(out_lines) + "\n", encoding="utf-8")
    return output_pdb


# ===================================================================
# VALIDATION
# ===================================================================
def validate_complex(complex_pdb: Path) -> dict:
    """Validate the docked complex: chain IDs, ligand in pocket, contacts."""
    info = {"valid": True, "warnings": [], "lig_atoms": 0,
            "min_contact": None, "pocket_dist": None}

    text = complex_pdb.read_text()
    prot_xyz, lig_xyz = [], []
    pocket_xyz = []

    for line in text.splitlines():
        if len(line) < 54:
            continue
        try:
            x = float(line[30:38])
            y = float(line[38:46])
            z = float(line[46:54])
        except (ValueError, IndexError):
            continue

        if line.startswith("ATOM") and line[21] == "A":
            prot_xyz.append([x, y, z])
            ri = int(line[22:26].strip())
            if ri in VDR_LBD_BINDING:
                pocket_xyz.append([x, y, z])
        elif line.startswith("HETATM") and line[21] == "B":
            lig_xyz.append([x, y, z])

    info["lig_atoms"] = len(lig_xyz)

    if not lig_xyz:
        info["valid"] = False
        info["warnings"].append("No ligand atoms")
        return info

    lig_cen = np.mean(lig_xyz, axis=0)

    if pocket_xyz:
        pocket_cen = np.mean(pocket_xyz, axis=0)
        pocket_dist = float(np.linalg.norm(lig_cen - pocket_cen))
        info["pocket_dist"] = pocket_dist
        if pocket_dist > 20.0:
            info["warnings"].append(f"Ligand {pocket_dist:.1f}A from pocket")

    if prot_xyz:
        prot_arr = np.array(prot_xyz)
        lig_arr = np.array(lig_xyz)
        # Minimum distance between any ligand atom and any protein atom
        min_d = float(np.min(
            np.linalg.norm(prot_arr[None, :, :] - lig_arr[:, None, :],
                           axis=2)))
        info["min_contact"] = min_d
        if min_d > 10.0:
            info["warnings"].append(f"Min contact {min_d:.1f}A (too far)")

    if info["warnings"]:
        info["valid"] = False
    return info


# ===================================================================
# PHARMACOPHORE VALIDATION (Glide XP-inspired)
# ===================================================================
def validate_pharmacophore(complex_pdb: Path) -> dict:
    """Check docked pose for key VDR H-bond interactions.

    1DB1 crystal H-bond network (Rochel et al., Mol Cell, 2000):
    25-OH anchors:  His305-NE2 (2.81 Å), His397-NE2 (2.82 Å)
    1α-OH anchors:  Arg274-NH1 (2.86 Å), Ser237-OG (2.78 Å)
    3β-OH anchors:  Tyr143-OH  (2.83 Å), Ser278-OG (2.91 Å)
    We measure distances from ligand polar atoms (O, N, S) to these
    six pharmacophoric anchor atoms.

    Returns dict: n_hbonds (0-6), pharmacophore_score, per-residue details.
    """
    pharm: dict = {"n_hbonds": 0, "pharmacophore_score": 0.0, "residues": {}}

    text = complex_pdb.read_text()
    key_xyz: dict[tuple[int, str], np.ndarray] = {}
    lig_polar: list[np.ndarray] = []

    for line in text.splitlines():
        if len(line) < 54:
            continue
        try:
            x = float(line[30:38])
            y = float(line[38:46])
            z = float(line[46:54])
        except (ValueError, IndexError):
            continue

        if line.startswith("ATOM") and line[21] == "A":
            try:
                rn = int(line[22:26].strip())
            except ValueError:
                continue
            aname = line[12:16].strip()
            if rn in PHARMACOPHORE:
                key_xyz[(rn, aname)] = np.array([x, y, z])
        elif line.startswith("HETATM") and line[21] == "B":
            elem = line[76:78].strip() if len(line) >= 78 else ""
            if not elem:
                elem = line[12:16].strip()[0] if line[12:16].strip() else "C"
            # Handle AutoDock atom types: OA->O, NA->N, SA->S, HD->H
            if len(elem) > 1:
                elem = elem[0]
            if elem in ("O", "N", "S"):
                lig_polar.append(np.array([x, y, z]))

    if not lig_polar or not key_xyz:
        return pharm

    for rn, info in PHARMACOPHORE.items():
        best_d = float("inf")
        for aname in info["atoms"]:
            if (rn, aname) not in key_xyz:
                continue
            for lp in lig_polar:
                d = float(np.linalg.norm(key_xyz[(rn, aname)] - lp))
                if d < best_d:
                    best_d = d

        satisfied = best_d <= HBOND_DIST_CUTOFF
        pharm["residues"][info["name"]] = {
            "dist": round(best_d, 2) if best_d < 999 else None,
            "satisfied": satisfied,
        }
        if satisfied:
            pharm["n_hbonds"] += 1
            pharm["pharmacophore_score"] += max(
                0, (HBOND_DIST_CUTOFF - best_d) / HBOND_DIST_CUTOFF)

    pharm["pharmacophore_score"] = round(pharm["pharmacophore_score"], 3)
    return pharm


# ===================================================================
# MAIN
# ===================================================================
def main():
    parser = argparse.ArgumentParser(
        description="AutoDock Vina docking into VDR LBD (prepared receptor)")
    parser.add_argument("--manifest", default=str(MANIFEST_PATH))
    parser.add_argument("--output", default=str(OUTPUT_DIR))
    parser.add_argument("--exhaustiveness", type=int, default=64,
                        help="Search thoroughness (8=fast, 32=good, 64=best)")
    parser.add_argument("--num-modes", type=int, default=9,
                        help="Max binding modes to generate")
    parser.add_argument("--energy-range", type=int, default=4,
                        help="Max energy diff from best mode (kcal/mol)")
    parser.add_argument("--seed", type=int, default=42,
                        help="Random seed for reproducibility")
    parser.add_argument("--timeout", type=int, default=600)
    parser.add_argument("--flexible", action="store_true", default=True,
                        help="Use flexible receptor residues (6 pharmacophore "
                             "anchors: Tyr143,Ser237,Arg274,Ser278,His305,His397)")
    parser.add_argument("--no-flexible", dest="flexible", action="store_false",
                        help="Use rigid receptor (no flexible residues)")
    parser.add_argument("--multi-state", action="store_true", default=False,
                        help="Glide-informed: dock tautomer x conformer variants")
    parser.add_argument("--max-tautomers", type=int, default=3,
                        help="Max tautomers per compound (multi-state)")
    parser.add_argument("--max-conformers", type=int, default=3,
                        help="Max conformers per tautomer (multi-state)")
    parser.add_argument("--start", type=int, default=0)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--skip-existing", action="store_true", default=True)
    parser.add_argument("--recompute-pharmacophore", action="store_true",
                        default=False,
                        help="Rebuild complex PDBs and recompute pharmacophore")
    args = parser.parse_args()

    # ── Pharmacophore post-processing mode ──────────────────────────
    if args.recompute_pharmacophore:
        out = Path(args.output)
        progress_csv = out / "progress.csv"
        complex_dir = out / "complex_pdbs"
        docked_dir = out / "docked_pdbqt"
        if not progress_csv.exists():
            print("ERROR: No progress.csv found"); sys.exit(1)
        df_prog = pd.read_csv(progress_csv)

        # Step 1: Rebuild complex PDBs from docked PDBQTs
        rebuilt = 0
        for idx, row in df_prog.iterrows():
            name = row["name"]
            # Try both naming conventions
            docked_file = docked_dir / f"{name}_out.pdbqt"
            if not docked_file.exists():
                docked_file = docked_dir / f"{name}_docked.pdbqt"
            cpdb_path = complex_dir / f"{name}_complex.pdb"
            if docked_file.exists():
                result = create_complex_pdb(RECEPTOR_PDB, docked_file, cpdb_path)
                if result:
                    rebuilt += 1
        print(f"Rebuilt {rebuilt} complex PDBs with corrected elements")

        # Step 2: Recompute pharmacophore on rebuilt complexes
        print(f"Recomputing pharmacophore for {len(df_prog)} compounds...")
        updated = 0
        for idx, row in df_prog.iterrows():
            cpdb_path = complex_dir / f"{row['name']}_complex.pdb"
            if not cpdb_path.exists():
                continue
            pharm = validate_pharmacophore(cpdb_path)
            df_prog.at[idx, "n_hbonds"] = pharm.get("n_hbonds", 0)
            df_prog.at[idx, "pharmacophore_score"] = pharm.get(
                "pharmacophore_score", 0.0)
            for rn_key, rn_info in PHARMACOPHORE.items():
                col = f"pharm_{rn_info['name']}"
                dist = pharm.get("residues", {}).get(
                    rn_info["name"], {}).get("dist")
                df_prog.at[idx, col] = dist
            updated += 1
        df_prog.to_csv(progress_csv, index=False)
        print(f"Updated {updated} rows in {progress_csv}")
        if "n_hbonds" in df_prog.columns:
            hb = df_prog["n_hbonds"].dropna()
            print(f"H-bonds: mean={hb.mean():.1f}  "
                  f"0-hb={int((hb==0).sum())}  1-hb={int((hb==1).sum())}  "
                  f"2-hb={int((hb==2).sum())}  3-hb={int((hb==3).sum())}  "
                  f"4-hb={int((hb==4).sum())}")
        sys.exit(0)

    # Validate prerequisites
    if not Path(VINA_EXE).exists():
        print(f"ERROR: Vina not found at {VINA_EXE}")
        sys.exit(1)
    if not RECEPTOR_PDBQT.exists():
        print(f"ERROR: Receptor PDBQT not found at {RECEPTOR_PDBQT}")
        print("  Generate with: python scripts/prepare_1db1_receptor.py")
        sys.exit(1)
    if not RECEPTOR_PDB.exists():
        print(f"ERROR: Receptor PDB not found at {RECEPTOR_PDB}")
        sys.exit(1)

    # Flexible receptor setup
    flex_path = None
    rec_path = RECEPTOR_PDBQT
    if args.flexible:
        if not RECEPTOR_RIGID.exists() or not RECEPTOR_FLEX.exists():
            print("ERROR: Rigid/Flex PDBQT not found. Run prepare_1db1_receptor.py first.")
            print(f"  Expected: {RECEPTOR_RIGID}")
            print(f"  Expected: {RECEPTOR_FLEX}")
            sys.exit(1)
        rec_path = RECEPTOR_RIGID
        flex_path = RECEPTOR_FLEX
        print(f"  Flexible docking: {RECEPTOR_FLEX.name}"
              f" (6 pharmacophore anchor residues)")

    df = pd.read_csv(args.manifest)
    if args.start > 0:
        df = df.iloc[args.start:]
    if args.limit is not None:
        df = df.iloc[:args.limit]

    out = Path(args.output)
    out.mkdir(parents=True, exist_ok=True)
    lig_dir = out / "ligand_pdbqt"
    lig_dir.mkdir(exist_ok=True)
    docked_dir = out / "docked_pdbqt"
    docked_dir.mkdir(exist_ok=True)
    logs_dir = out / "logs"
    logs_dir.mkdir(exist_ok=True)
    complex_dir = out / "complex_pdbs"
    complex_dir.mkdir(exist_ok=True)
    progress_csv = out / "progress.csv"

    # Resume support
    done_names = set()
    if progress_csv.exists():
        prev = pd.read_csv(progress_csv)
        done_names = set(prev[prev["status"] == "success"]["name"])

    total = len(df)
    to_do = sum(
        1 for _, row in df.iterrows()
        if f"{row['source']}_{row['csv_row']}" not in done_names
    )

    print("=" * 70)
    print("AUTODOCK VINA DOCKING -- VDR LBD (1DB1 crystal, 250 res)")
    print("=" * 70)
    print(f"Receptor:  {RECEPTOR_PDBQT.name} (res 120-423, 1DB1 crystal, pH 7.4)")
    print(f"Pocket:    {VDR_LBD_BINDING} (LBD numbering)")
    print(f"Box center: ({BOX_CENTER[0]:.2f}, {BOX_CENTER[1]:.2f},"
          f" {BOX_CENTER[2]:.2f})")
    print(f"Box size:   ({BOX_SIZE[0]:.0f}, {BOX_SIZE[1]:.0f},"
          f" {BOX_SIZE[2]:.0f}) A")
    flex_tag = "  FLEX=6-res" if args.flexible else "  RIGID"
    ms_tag = (f"  multi-state={args.max_tautomers}t x {args.max_conformers}c"
              if args.multi_state else "  single-state")
    print(f"Settings:  exhaust={args.exhaustiveness}  modes={args.num_modes}"
          f"  E-range={args.energy_range}  seed={args.seed}{flex_tag}{ms_tag}")
    print(f"Total:     {total} compounds | Done: {len(done_names)}"
          f" | Remaining: {to_do}")
    print("=" * 70)

    rows: list[dict] = []
    n_ok, n_fail, n_skip = 0, 0, 0
    times: list[float] = []
    t_start = time.time()

    for i, (_, row) in enumerate(df.iterrows()):
        src = row["source"]
        csvr = row["csv_row"]
        name = f"{src}_{csvr}"
        tag = f"[{i+1}/{total}]"

        if args.skip_existing and name in done_names:
            n_skip += 1
            continue

        smiles = row["smiles"]
        smi_short = (smiles[:55] + "...") if len(smiles) > 55 else smiles
        print(f"\n{tag} {name}  {smi_short}")

        # ── Step 1 + 2: Ligand prep → Vina docking ─────────────
        if args.multi_state:
            # Glide-informed: enumerate tautomers x conformers
            variants = smiles_to_pdbqt_variants(
                smiles, name, lig_dir,
                max_tautomers=args.max_tautomers,
                max_conformers=args.max_conformers,
            )
            if not variants:
                print(f"  FAIL (prep): no valid variants")
                rows.append({
                    "name": name, "source": src, "csv_row": csvr,
                    "smiles": smiles, "status": "failed_prep",
                    "error": "no variants",
                })
                n_fail += 1
                continue

            print(f"  Multi-state: {len(variants)} variants")
            best_score = None
            best_variant = None
            total_elapsed = 0.0

            for vpdbqt, vlabel in variants:
                vok, vmsg, vel, vsc = run_vina(
                    vpdbqt, docked_dir, vlabel,
                    receptor=rec_path,
                    flex_receptor=flex_path,
                    exhaustiveness=args.exhaustiveness,
                    num_modes=args.num_modes,
                    energy_range=args.energy_range,
                    seed=args.seed,
                    timeout=args.timeout,
                )
                total_elapsed += vel or 0.0
                vlog = docked_dir / f"{vlabel}_log.txt"
                if vlog.exists():
                    shutil.move(str(vlog),
                                str(logs_dir / f"{vlabel}_log.txt"))
                if vok and vsc is not None:
                    if best_score is None or vsc < best_score:
                        best_score = vsc
                        best_variant = vlabel

            if best_score is None:
                print(f"  FAIL (dock): all {len(variants)} variants failed")
                rows.append({
                    "name": name, "source": src, "csv_row": csvr,
                    "smiles": smiles, "status": "failed_dock",
                    "error": "all variants failed",
                    "elapsed": total_elapsed,
                })
                n_fail += 1
                continue

            ok, elapsed, msg = True, total_elapsed, f"best={best_variant}"
            # Copy best variant outputs to standard names
            bv_out = docked_dir / f"{best_variant}_out.pdbqt"
            std_out = docked_dir / f"{name}_out.pdbqt"
            if bv_out.exists():
                shutil.copy2(str(bv_out), str(std_out))
            bv_log = logs_dir / f"{best_variant}_log.txt"
            std_log = logs_dir / f"{name}_log.txt"
            if bv_log.exists():
                shutil.copy2(str(bv_log), str(std_log))

        else:
            # Original single-state pipeline
            prep_ok, prep_msg, lig_pdbqt = smiles_to_pdbqt(
                smiles, name, lig_dir)
            if not prep_ok:
                print(f"  FAIL (prep): {prep_msg}")
                rows.append({
                    "name": name, "source": src, "csv_row": csvr,
                    "smiles": smiles, "status": "failed_prep",
                    "error": prep_msg,
                })
                n_fail += 1
                continue

            ok, msg, elapsed, best_score = run_vina(
                lig_pdbqt, docked_dir, name,
                receptor=rec_path,
                flex_receptor=flex_path,
                exhaustiveness=args.exhaustiveness,
                num_modes=args.num_modes,
                energy_range=args.energy_range,
                seed=args.seed,
                timeout=args.timeout,
            )
            dock_log = docked_dir / f"{name}_log.txt"
            if dock_log.exists():
                shutil.move(str(dock_log),
                            str(logs_dir / f"{name}_log.txt"))

        if not ok:
            print(f"  FAIL (dock): {msg}")
            rows.append({
                "name": name, "source": src, "csv_row": csvr,
                "smiles": smiles, "status": "failed_dock", "error": msg,
                "elapsed": elapsed,
            })
            n_fail += 1
        else:
            # Parse all scores
            log_path = logs_dir / f"{name}_log.txt"
            all_scores = parse_all_scores(log_path)
            n_modes = len(all_scores)

            # Step 3: Create complex PDB (receptor + best pose)
            docked_file = docked_dir / f"{name}_out.pdbqt"
            complex_pdb = complex_dir / f"{name}_complex.pdb"
            cpdb = create_complex_pdb(RECEPTOR_PDB, docked_file, complex_pdb)

            # Step 4: Validate complex
            val = {}
            if cpdb:
                val = validate_complex(cpdb)

            # Step 5: Pharmacophore check (Glide XP-inspired)
            pharm = {}
            if cpdb:
                pharm = validate_pharmacophore(cpdb)
            n_hb = pharm.get("n_hbonds", 0)
            pscore = pharm.get("pharmacophore_score", 0.0)

            cpdb_str = str(cpdb) if cpdb else None
            contact_s = (f"contact={val['min_contact']:.1f}A"
                         if val.get("min_contact") else "")
            pocket_s = (f"pocket={val['pocket_dist']:.1f}A"
                        if val.get("pocket_dist") else "")

            score_s = f"{best_score:.2f}" if best_score is not None else "?"
            status_tag = "OK" if cpdb else "NO-PDB"
            hb_s = f"Hbond={n_hb}/6"
            print(f"  {status_tag}  score={score_s} kcal/mol  modes={n_modes}"
                  f"  {contact_s}  {pocket_s}  {hb_s}  ({elapsed:.0f}s)")

            if val.get("warnings"):
                for w in val["warnings"]:
                    print(f"    WARNING: {w}")

            # Per-residue pharmacophore details
            for rname, rdata in pharm.get("residues", {}).items():
                d_str = f"{rdata['dist']:.1f}A" if rdata.get('dist') else "N/A"
                tag_s = "OK" if rdata.get("satisfied") else "--"
                print(f"    {tag_s} {rname}: {d_str}")

            times.append(elapsed)
            n_ok += 1

            rows.append({
                "name": name, "source": src, "csv_row": csvr,
                "smiles": smiles, "status": "success",
                "vina_score": best_score,
                "n_modes": n_modes,
                "all_scores": ";".join(f"{s:.2f}" for s in all_scores),
                "complex_pdb": cpdb_str,
                "min_contact": val.get("min_contact"),
                "pocket_dist": val.get("pocket_dist"),
                "lig_atoms": val.get("lig_atoms"),
                "n_hbonds": n_hb,
                "pharmacophore_score": pscore,
                "pharm_His305": pharm.get("residues", {}).get("His305", {}).get("dist"),
                "pharm_His397": pharm.get("residues", {}).get("His397", {}).get("dist"),
                "pharm_Arg274": pharm.get("residues", {}).get("Arg274", {}).get("dist"),
                "pharm_Ser237": pharm.get("residues", {}).get("Ser237", {}).get("dist"),
                "pharm_Tyr143": pharm.get("residues", {}).get("Tyr143", {}).get("dist"),
                "pharm_Ser278": pharm.get("residues", {}).get("Ser278", {}).get("dist"),
                "elapsed": elapsed,
            })

        # Save progress + ETA
        batch_df = pd.DataFrame(rows)
        if progress_csv.exists():
            prev = pd.read_csv(progress_csv)
            prev = prev[~prev["name"].isin(batch_df["name"])]
            batch_df = pd.concat([prev, batch_df], ignore_index=True)
        batch_df.to_csv(progress_csv, index=False)

        done_so_far = n_ok + n_fail
        if times:
            avg_t = np.mean(times)
            remaining = to_do - done_so_far
            eta_min = remaining * avg_t / 60
            print(f"  ETA: {eta_min:.0f} min ({eta_min/60:.1f}h) | "
                  f"avg={avg_t:.0f}s/cpd | done={done_so_far}/{to_do}")

    # Final summary
    wall = time.time() - t_start
    print("\n" + "=" * 70)
    print("SUMMARY")
    print("=" * 70)
    print(f"  Success: {n_ok}  |  Failed: {n_fail}  |  Skipped: {n_skip}")
    print(f"  Wall time: {wall/60:.1f} min")
    if times:
        print(f"  Avg time:  {np.mean(times):.1f}s/compound")
    print(f"  Output:    {out}")
    print(f"  Complexes: {complex_dir}")
    print(f"  Progress:  {progress_csv}")

    if progress_csv.exists():
        final = pd.read_csv(progress_csv)
        if "vina_score" in final.columns:
            vals = final["vina_score"].dropna()
            if len(vals) > 0:
                print(f"\n  Vina scores: mean={vals.mean():.2f}"
                      f"  best={vals.min():.2f}  worst={vals.max():.2f}")
                top10 = final.nsmallest(10, "vina_score")[
                    ["name", "vina_score"]]
                print("\n  Top 10 by Vina score:")
                for _, r in top10.iterrows():
                    print(f"    {r['name']:15s}"
                          f"  {r['vina_score']:.2f} kcal/mol")

        if "min_contact" in final.columns:
            mc = final["min_contact"].dropna()
            if len(mc) > 0:
                print(f"\n  Min contact: mean={mc.mean():.1f}A"
                      f"  min={mc.min():.1f}A  max={mc.max():.1f}A")

        if "n_hbonds" in final.columns:
            hb = final["n_hbonds"].dropna()
            if len(hb) > 0:
                print(f"\n  Pharmacophore H-bonds (of 6 VDR anchors):")
                print(f"    mean={hb.mean():.1f}  "
                      f"0-hb={int((hb==0).sum())}  "
                      f"1-hb={int((hb==1).sum())}  "
                      f"2-hb={int((hb==2).sum())}  "
                      f"3-hb={int((hb==3).sum())}  "
                      f"4-hb={int((hb==4).sum())}  "
                      f"5-hb={int((hb==5).sum())}  "
                      f"6-hb={int((hb==6).sum())}")

        n_complex = final["complex_pdb"].notna().sum() if "complex_pdb" in final.columns else 0
        print(f"  Complex PDBs: {n_complex}/{len(final)}")


if __name__ == "__main__":
    main()
